"""
Email Alerts — sends trading signals via Gmail SMTP.

Setup:
    1. Enable 2FA on your Google account
    2. Create an App Password: https://myaccount.google.com/apppasswords
    3. Add to .env:
        EMAIL_SENDER=your_email@gmail.com
        EMAIL_APP_PASSWORD=your_16_char_app_password
        EMAIL_RECIPIENT=your_email@gmail.com (or multiple, comma-separated)
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

from auth.login import load_env


def _get_config() -> dict:
    load_env()
    return {
        "sender": os.environ.get("EMAIL_SENDER", ""),
        "password": os.environ.get("EMAIL_APP_PASSWORD", ""),
        "recipients": [r.strip() for r in os.environ.get("EMAIL_RECIPIENT", "").split(",") if r.strip()],
    }


def _format_html(signals: list[dict]) -> str:
    """Generate an HTML email body for the signals."""
    now = datetime.now().strftime("%d %b %Y, %I:%M %p")

    rows = ""
    for s in signals:
        color = s.get("color", "#22c55e" if s["signal_type"] == "BUY" else "#ef4444")
        bg = "#f0fdf4" if s["signal_type"] == "BUY" else "#fef2f2"
        strength = s.get("strength", s.get("signal_type", "BUY"))
        # Strategy column: show count + names
        if "strategies" in s:
            strat_text = f"{s['strategy_count']}x: {', '.join(s['strategies'])}"
        else:
            strat_text = s.get("strategy", "")
        # Reason column: show all reasons
        if "reasons" in s:
            reason_text = "<br>".join(f"&#8226; {r[:55]}" for r in s["reasons"])
        else:
            reason_text = s.get("reason", "")[:60]
        rows += f"""
        <tr style="background:{bg}">
            <td style="padding:10px;border-bottom:1px solid #e5e7eb;font-weight:bold">{s['symbol_name']}</td>
            <td style="padding:10px;border-bottom:1px solid #e5e7eb">
                <span style="background:{color};color:white;padding:2px 8px;border-radius:4px;font-weight:bold;font-size:11px">
                    {strength}
                </span>
            </td>
            <td style="padding:10px;border-bottom:1px solid #e5e7eb;font-size:12px">{strat_text}</td>
            <td style="padding:10px;border-bottom:1px solid #e5e7eb">₹{s['price']:.2f}</td>
            <td style="padding:10px;border-bottom:1px solid #e5e7eb">₹{s['stop_loss']:.2f}</td>
            <td style="padding:10px;border-bottom:1px solid #e5e7eb">₹{s['target']:.2f}</td>
            <td style="padding:10px;border-bottom:1px solid #e5e7eb">{s['confidence']:.0%}</td>
            <td style="padding:10px;border-bottom:1px solid #e5e7eb;font-size:11px">{reason_text}</td>
        </tr>"""

    html = f"""
    <html>
    <body style="font-family:Arial,sans-serif;max-width:900px;margin:0 auto;padding:20px">
        <h2 style="color:#1e293b">🚨 Stock Scanner Alert</h2>
        <p style="color:#64748b">{len(signals)} signal(s) detected — {now}</p>

        <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden">
            <thead>
                <tr style="background:#1e293b;color:white">
                    <th style="padding:10px;text-align:left">Symbol</th>
                    <th style="padding:10px;text-align:left">Signal</th>
                    <th style="padding:10px;text-align:left">Strategy</th>
                    <th style="padding:10px;text-align:right">Price</th>
                    <th style="padding:10px;text-align:right">Stop Loss</th>
                    <th style="padding:10px;text-align:right">Target</th>
                    <th style="padding:10px;text-align:right">Conf</th>
                    <th style="padding:10px;text-align:left">Reason</th>
                </tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>

        <p style="color:#94a3b8;font-size:12px;margin-top:20px">
            Generated by Fyers Stock Scanner | Not financial advice
        </p>
    </body>
    </html>
    """
    return html


def send_email_alerts(signals: list[dict], sender: str = "", password: str = "", recipients: list[str] | None = None) -> bool:
    """Send signal alerts via email."""
    config = _get_config()
    sender = sender or config["sender"]
    password = password or config["password"]
    recipients = recipients or config["recipients"]

    if not sender or not password or not recipients:
        print("Email not configured. Set EMAIL_SENDER, EMAIL_APP_PASSWORD, EMAIL_RECIPIENT in .env")
        return False

    now = datetime.now().strftime("%d %b %Y, %I:%M %p")
    subject = f"🚨 Scanner Alert — {len(signals)} signal(s) — {now}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"Stock Scanner <{sender}>"
    msg["To"] = ", ".join(recipients)

    # Plain text version
    plain = f"Stock Scanner Alert — {len(signals)} signal(s)\n\n"
    for s in signals:
        strength = s.get('strength', s.get('signal_type', 'BUY'))
        if 'strategies' in s:
            strat_text = f"{s['strategy_count']}x: {', '.join(s['strategies'])}"
        else:
            strat_text = s.get('strategy', '')
        if 'reasons' in s:
            reasons = " | ".join(s['reasons'])
        else:
            reasons = s.get('reason', '')
        plain += f"{strength} {s['symbol_name']} @ ₹{s['price']:.2f}\n"
        plain += f"  {strat_text} | SL: ₹{s['stop_loss']:.2f} | Target: ₹{s['target']:.2f}\n"
        plain += f"  {reasons}\n\n"

    html = _format_html(signals)

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    try:
        import ssl as _ssl
        context = _ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(sender, password)
            server.sendmail(sender, recipients, msg.as_string())
        print(f"Email sent to {', '.join(recipients)}")
        return True
    except Exception as e:
        print(f"Email error: {e}")
        return False
